/**
 * This file is autogenerated by Scaffold-HBAR deployments.
 * The inherited template deployments were not produced by Forklab, so no
 * deployment is claimed until DeployRecurringBuy.s.sol runs successfully.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
