/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    RecurringBuy: {
      address: "0xf75d7f902a8ce0e8a21bbf51bd7bf66420eba9a5",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "supraAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "routerAddress",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "DEFAULT_MAX_PRICE_AGE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "HBAR_USD_PAIR_INDEX",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "amountPerBuy",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "bonzoPool",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "configure",
          inputs: [
            {
              name: "tokenOutAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "amountTinybars",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "intervalSeconds",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "deviationBps",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "priceAgeSeconds",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "configureBonzo",
          inputs: [
            {
              name: "pool",
              type: "address",
              internalType: "address",
            },
            {
              name: "enabled",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "deposit",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "execute",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "hbarBalance",
          inputs: [],
          outputs: [
            {
              name: "balanceTinybars",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "interval",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isVaultAssociated",
          inputs: [],
          outputs: [
            {
              name: "associated",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "lastRunAt",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "lastScheduleStatus",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "int64",
              internalType: "int64",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "maxDeviationBps",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "maxPriceAge",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextRunAt",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextSchedule",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "router",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract ISaucerSwapRouterRecurringBuy",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "running",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "start",
          inputs: [],
          outputs: [
            {
              name: "responseCode",
              type: "int64",
              internalType: "int64",
            },
            {
              name: "scheduleAddress",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "stop",
          inputs: [],
          outputs: [
            {
              name: "responseCode",
              type: "int64",
              internalType: "int64",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "supra",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract ISupraSValueFeed",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sweepToBonzo",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "tokenOut",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "whbar",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [
            {
              name: "amountTinybars",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "BonzoSweepConfigured",
          inputs: [
            {
              name: "pool",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "enabled",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Bought",
          inputs: [
            {
              name: "hbarAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "tokenAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "oracleAmountOut",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "poolAmountOut",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ScheduleCreated",
          inputs: [
            {
              name: "schedule",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "runAt",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ScheduleFailed",
          inputs: [
            {
              name: "responseCode",
              type: "int64",
              indexed: true,
              internalType: "int64",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SkippedDeviation",
          inputs: [
            {
              name: "oracleAmountOut",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "poolAmountOut",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "deviationBps",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SkippedStalePrice",
          inputs: [
            {
              name: "publishTime",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "currentTime",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Stopped",
          inputs: [
            {
              name: "responseCode",
              type: "int64",
              indexed: false,
              internalType: "int64",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SweptToBonzo",
          inputs: [
            {
              name: "asset",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "onBehalfOf",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "HbarTransferFailed",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidConfiguration",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidOwner",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidSupraPrice",
          inputs: [],
        },
        {
          type: "error",
          name: "NotOwner",
          inputs: [],
        },
        {
          type: "error",
          name: "OnlyVault",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnerTokenAssociationRequired",
          inputs: [],
        },
        {
          type: "error",
          name: "TokenAssociationFailed",
          inputs: [
            {
              name: "responseCode",
              type: "int64",
              internalType: "int64",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41352354,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
